services:
  backend:
    build: .
    command: python -m risklive.server.app
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dashboard:
    build: .
    command: >
      sh -c "
      echo 'Waiting for backend to be ready...';
      until curl -f http://backend:5000/health 2>/dev/null; do
        echo 'Backend not ready yet, waiting...';
        sleep 2;
      done;
      echo 'Backend is ready! Starting dashboard...';
      streamlit run risklive/dashboard/TopicModel.py --server.port=8501 --server.address=0.0.0.0
      "
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
